# Generated by Django 4.2.11 on 2025-09-14 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_approve_article', 'Can approve articles'), ('can_create_article', 'Can create articles')]},
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('readers', 'Readers Only'), ('journalists', 'Journalists Only'), ('editors', 'Editors Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_newsletter', 'Can create newsletters'), ('can_send_newsletter', 'Can send newsletters')],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='core.newsletter'),
        ),
    ]
